//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebUI.Admin
{


    public partial class CylinderPrintPage
    {
        protected global::System.Web.UI.WebControls.Label txtCustomer;
        protected global::System.Web.UI.WebControls.Label txtProductionName;
        protected global::System.Web.UI.WebControls.Label txtOrderCode;
        protected global::System.Web.UI.WebControls.Label txtType;
        protected global::System.Web.UI.WebControls.Label txtDiameter;
        protected global::System.Web.UI.WebControls.Label txtLength;
        protected global::System.Web.UI.WebControls.Label txtArea;
        protected global::System.Web.UI.WebControls.Label txtCircumference;
        protected global::System.Web.UI.WebControls.Label txtKeyhole;
        protected global::System.Web.UI.WebControls.Label txtKeyway;
        protected global::System.Web.UI.WebControls.Image imgBarCode;
    }
}
