//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.239
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "10.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AccessRights_VN {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AccessRights_VN() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.AccessRights_VN", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duyệt Cấp Quyền.
        /// </summary>
        internal static string Approve_Assign_Roles {
            get {
                return ResourceManager.GetString("Approve Assign Roles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Khách Hàng.
        /// </summary>
        internal static string Customer {
            get {
                return ResourceManager.GetString("Customer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thông Tin Trục.
        /// </summary>
        internal static string Cylinder_Info {
            get {
                return ResourceManager.GetString("Cylinder Info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quản Lý Nhân Viên.
        /// </summary>
        internal static string Employee_Management {
            get {
                return ResourceManager.GetString("Employee Management", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chấm Điểm Nhân Viên.
        /// </summary>
        internal static string Employee_Performance {
            get {
                return ResourceManager.GetString("Employee Performance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quản Lý Đơn Hàng.
        /// </summary>
        internal static string Order_Management {
            get {
                return ResourceManager.GetString("Order Management", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Báo Cáo.
        /// </summary>
        internal static string Report {
            get {
                return ResourceManager.GetString("Report", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role Assignment Approval.
        /// </summary>
        internal static string Role_Assignment_Approval {
            get {
                return ResourceManager.GetString("Role Assignment Approval", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quản Lý Vai Trò.
        /// </summary>
        internal static string Role_Management {
            get {
                return ResourceManager.GetString("Role Management", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chuyển Trục Đến Bước Khác.
        /// </summary>
        internal static string Send_to_workflow_step {
            get {
                return ResourceManager.GetString("Send to workflow/step", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Danh Sách Bước.
        /// </summary>
        internal static string Step_List {
            get {
                return ResourceManager.GetString("Step List", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xem Lịch SX.
        /// </summary>
        internal static string View_Current_Queue {
            get {
                return ResourceManager.GetString("View Current Queue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lỗi Công Việc.
        /// </summary>
        internal static string Workflow_Error {
            get {
                return ResourceManager.GetString("Workflow Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quản Lý Quy Trình SX.
        /// </summary>
        internal static string Workflow_Management {
            get {
                return ResourceManager.GetString("Workflow Management", resourceCulture);
            }
        }
    }
}
