//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.239
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "10.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Departments_EN {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Departments_EN() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Departments_EN", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Engraving-Lasering Dept.
        /// </summary>
        internal static string Engraving_Lasering_Dept {
            get {
                return ResourceManager.GetString("Engraving-Lasering Dept", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Graphic-Repro Dept.
        /// </summary>
        internal static string Graphic_Repro_Dept {
            get {
                return ResourceManager.GetString("Graphic-Repro Dept", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mechanical Dept.
        /// </summary>
        internal static string Mechanical_Dept {
            get {
                return ResourceManager.GetString("Mechanical Dept", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Printing Dept.
        /// </summary>
        internal static string Printing_Dept {
            get {
                return ResourceManager.GetString("Printing Dept", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Production Dept.
        /// </summary>
        internal static string Production_Dept {
            get {
                return ResourceManager.GetString("Production Dept", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Production Mgmt Dept.
        /// </summary>
        internal static string Production_Mgmt_Dept {
            get {
                return ResourceManager.GetString("Production Mgmt Dept", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quality Control 2 Dept.
        /// </summary>
        internal static string Quality_Control_2_Dept {
            get {
                return ResourceManager.GetString("Quality Control 2 Dept", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sales Dept.
        /// </summary>
        internal static string Sales_Dept {
            get {
                return ResourceManager.GetString("Sales Dept", resourceCulture);
            }
        }
    }
}
