//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Data.EntityClient;
using System.ComponentModel;
using System.Xml.Serialization;
using System.Runtime.Serialization;

[assembly: EdmSchemaAttribute()]
#region EDM Relationship Metadata

[assembly: EdmRelationshipAttribute("Workflow", "WorkflowStep", "Workflow", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(WorkflowApplication.Workflow), "Step", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(WorkflowApplication.Step))]

#endregion

namespace WorkflowApplication
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class WorkflowContainer : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new WorkflowContainer object using the connection string found in the 'WorkflowContainer' section of the application configuration file.
        /// </summary>
        public WorkflowContainer() : base("name=WorkflowContainer", "WorkflowContainer")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new WorkflowContainer object.
        /// </summary>
        public WorkflowContainer(string connectionString) : base(connectionString, "WorkflowContainer")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new WorkflowContainer object.
        /// </summary>
        public WorkflowContainer(EntityConnection connection) : base(connection, "WorkflowContainer")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Workflow> Workflows
        {
            get
            {
                if ((_Workflows == null))
                {
                    _Workflows = base.CreateObjectSet<Workflow>("Workflows");
                }
                return _Workflows;
            }
        }
        private ObjectSet<Workflow> _Workflows;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Step> Steps
        {
            get
            {
                if ((_Steps == null))
                {
                    _Steps = base.CreateObjectSet<Step>("Steps");
                }
                return _Steps;
            }
        }
        private ObjectSet<Step> _Steps;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<ActivityBlock> ActivityBlocks
        {
            get
            {
                if ((_ActivityBlocks == null))
                {
                    _ActivityBlocks = base.CreateObjectSet<ActivityBlock>("ActivityBlocks");
                }
                return _ActivityBlocks;
            }
        }
        private ObjectSet<ActivityBlock> _ActivityBlocks;

        #endregion
        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Workflows EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToWorkflows(Workflow workflow)
        {
            base.AddObject("Workflows", workflow);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Steps EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToSteps(Step step)
        {
            base.AddObject("Steps", step);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the ActivityBlocks EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToActivityBlocks(ActivityBlock activityBlock)
        {
            base.AddObject("ActivityBlocks", activityBlock);
        }

        #endregion
    }
    

    #endregion
    
    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="Workflow", Name="ActivityBlock")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class ActivityBlock : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new ActivityBlock object.
        /// </summary>
        /// <param name="activityBlockID">Initial value of the ActivityBlockID property.</param>
        public static ActivityBlock CreateActivityBlock(global::System.Int32 activityBlockID)
        {
            ActivityBlock activityBlock = new ActivityBlock();
            activityBlock.ActivityBlockID = activityBlockID;
            return activityBlock;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ActivityBlockID
        {
            get
            {
                return _ActivityBlockID;
            }
            set
            {
                if (_ActivityBlockID != value)
                {
                    OnActivityBlockIDChanging(value);
                    ReportPropertyChanging("ActivityBlockID");
                    _ActivityBlockID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ActivityBlockID");
                    OnActivityBlockIDChanged();
                }
            }
        }
        private global::System.Int32 _ActivityBlockID;
        partial void OnActivityBlockIDChanging(global::System.Int32 value);
        partial void OnActivityBlockIDChanged();

        #endregion
    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="Workflow", Name="Step")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Step : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Step object.
        /// </summary>
        /// <param name="stepID">Initial value of the StepID property.</param>
        public static Step CreateStep(global::System.Int32 stepID)
        {
            Step step = new Step();
            step.StepID = stepID;
            return step;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 StepID
        {
            get
            {
                return _StepID;
            }
            set
            {
                if (_StepID != value)
                {
                    OnStepIDChanging(value);
                    ReportPropertyChanging("StepID");
                    _StepID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("StepID");
                    OnStepIDChanged();
                }
            }
        }
        private global::System.Int32 _StepID;
        partial void OnStepIDChanging(global::System.Int32 value);
        partial void OnStepIDChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Workflow", "WorkflowStep", "Workflow")]
        public Workflow Workflow
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Workflow>("Workflow.WorkflowStep", "Workflow").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Workflow>("Workflow.WorkflowStep", "Workflow").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Workflow> WorkflowReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Workflow>("Workflow.WorkflowStep", "Workflow");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Workflow>("Workflow.WorkflowStep", "Workflow", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="Workflow", Name="Workflow")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Workflow : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Workflow object.
        /// </summary>
        /// <param name="workflowID">Initial value of the WorkflowID property.</param>
        /// <param name="name">Initial value of the Name property.</param>
        public static Workflow CreateWorkflow(global::System.Int32 workflowID, global::System.String name)
        {
            Workflow workflow = new Workflow();
            workflow.WorkflowID = workflowID;
            workflow.Name = name;
            return workflow;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 WorkflowID
        {
            get
            {
                return _WorkflowID;
            }
            set
            {
                if (_WorkflowID != value)
                {
                    OnWorkflowIDChanging(value);
                    ReportPropertyChanging("WorkflowID");
                    _WorkflowID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("WorkflowID");
                    OnWorkflowIDChanged();
                }
            }
        }
        private global::System.Int32 _WorkflowID;
        partial void OnWorkflowIDChanging(global::System.Int32 value);
        partial void OnWorkflowIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Name
        {
            get
            {
                return _Name;
            }
            set
            {
                OnNameChanging(value);
                ReportPropertyChanging("Name");
                _Name = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Name");
                OnNameChanged();
            }
        }
        private global::System.String _Name;
        partial void OnNameChanging(global::System.String value);
        partial void OnNameChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Workflow", "WorkflowStep", "Step")]
        public EntityCollection<Step> Steps
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Step>("Workflow.WorkflowStep", "Step");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Step>("Workflow.WorkflowStep", "Step", value);
                }
            }
        }

        #endregion
    }

    #endregion
    
}
